plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
}

group 'org.delivery'
version '1.0-SNAPSHOT'
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    //testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    //testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'

    implementation group: 'jakarta.validation', name: 'jakarta.validation-api', version: '3.0.2'

    implementation group: 'org.springframework', name: 'spring-core', version: '6.2.2'

    implementation group: 'org.springframework', name: 'spring-context', version: '6.2.2'

    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")

}


test {
    useJUnitPlatform()
}

jar {
    enabled = true
}

kotlin {
    jvmToolchain(21) // Kotlin도 Java 21 적용
    compilerOptions {
        freeCompilerArgs.addAll("-Xjsr305=strict") // 문자열 리터럴 문제 해결
    }
}